/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Language = "zh-CN" | "zh-TW" | "en" | "ja" | "ko";
export type Translate = (key: string, variables?: Record<string, string | number>) => string;

// Language preference is app-local UI state. It is persisted separately from
// workspace records so opening another workspace does not change the language.
const LANGUAGE_STORAGE_KEY = "studypulse.language";

// The option order is also the stable order used by the Settings select; keep
// values aligned with the dictionary keys and browser-language detection.
export const languageOptions: { value: Language; label: string }[] = [
  { value: "zh-CN", label: "简体中文" },
  { value: "zh-TW", label: "繁體中文" },
  { value: "en", label: "English" },
  { value: "ja", label: "日本語" },
  { value: "ko", label: "한국어" },
];

function detectLanguage(): Language {
  // Detection prefers an explicit local choice, then maps browser locale
  // prefixes. Server/Node rendering has no browser and safely defaults to en.
  if (typeof window === "undefined") return "en";
  const saved = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (languageOptions.some((option) => option.value === saved)) return saved as Language;
  const browserLanguage = navigator.language.toLowerCase();
  if (browserLanguage.startsWith("zh-tw") || browserLanguage.startsWith("zh-hk") || browserLanguage.startsWith("zh-mo")) return "zh-TW";
  if (browserLanguage.startsWith("zh")) return "zh-CN";
  if (browserLanguage.startsWith("ja")) return "ja";
  if (browserLanguage.startsWith("ko")) return "ko";
  return "en";
}

// `en` is the fallback dictionary and also documents the complete base key
// space. Feature dictionaries below are merged into it by language.
const en: Record<string, string> = {
  "nav.today": "Today", "nav.agent": "Agent", "nav.tasks": "Tasks", "nav.subjects": "Subjects & Grades", "nav.exams": "Exams", "nav.mistakes": "Mistakes", "nav.timer": "Study Timer", "nav.investment": "Time Investment", "nav.library": "Library", "nav.settings": "Settings", "nav.aria": "StudyPulse sections",
  "brand.localWorkspace": "Local-first workspace", "workspace.default": "Workspace", "local.stored": "Stored on this Mac",
  "top.learningRhythm": "Your learning rhythm", "top.greeting": "Good to see you.", "top.importBackup": "Import backup", "top.exportBackup": "Export backup",
  "loading.opening": "Opening your local workspace…", "loading.failed": "StudyPulse could not start", "common.retry": "Retry", "error.generic": "Something went wrong.", "error.section": "Could not load this section",
  "welcome.eyebrow": "A quiet place to make progress", "welcome.title": "Your learning workspace, kept close.", "welcome.copy": "StudyPulse keeps your data in a local Workspace. Open an existing one or create a new place for tasks, notes, sessions and Agent work.", "welcome.create": "Create workspace", "welcome.open": "Open workspace", "welcome.localTitle": "Local-first by default", "welcome.localCopy": "Cloud AI is optional. Your Workspace stays on this Mac.",
  "backup.conflicts": "{count} conflicts need review.", "backup.ready": "Backup schema {schema} is ready. {records} new records.", "backup.applyReplace": "Apply Replace restore now?", "backup.exported": "Backup exported successfully.",
  "today.heroTitle": "Small, consistent steps", "today.heroEmphasis": "compound.", "today.heroCopy": "Keep the next useful thing close.", "today.openTasks": "Open tasks", "today.nothingUrgent": "Nothing urgent", "today.studyTime": "Study time", "today.streak": "{count}-day streak", "today.dueMistakes": "Due mistakes", "today.readyReview": "Ready for review", "today.upcomingExams": "Upcoming exams", "today.noExamsSoon": "No exams soon", "today.nextTitle": "Next on your desk", "today.nextDescription": "A short list is a kind list.", "today.general": "General", "today.due": "Due {date}", "today.high": "High", "today.focus": "Focus", "today.clearTitle": "Your desk is clear", "today.clearCopy": "Create a task when the next thing becomes clear.", "today.noteTitle": "Today’s note", "today.noteDescription": "A gentle check-in.", "today.quote": "“The goal is not to hold everything in your head. It is to build a place you can return to.”",
  "tasks.title": "Tasks", "tasks.description": "A manageable queue for the work that matters.", "tasks.addPlaceholder": "Add a task…", "tasks.saving": "Saving…", "common.add": "Add", "tasks.noTasks": "No tasks yet", "tasks.noTasksCopy": "Add one small next step above.", "tasks.validation": "Please enter a task title.",
  "subjects.title": "Subjects & Grades", "subjects.description": "Keep the shape of your academic progress visible.", "subjects.subjectsTitle": "Subjects", "subjects.subjectsDescription": "A stable vocabulary for your study data.", "subjects.newSubject": "New subject", "subjects.fullScore": "Full score", "subjects.addSubject": "Add subject", "subjects.active": "Active", "subjects.off": "Off", "subjects.none": "No subjects yet", "subjects.noneCopy": "Add the first subject to start tracking grades.", "subjects.gradesTitle": "Grades", "subjects.gradesDescription": "Capture a result without leaving the local workspace.", "subjects.examOptional": "Exam name (optional)", "subjects.score": "Score", "subjects.addGrade": "Add grade", "subjects.grade": "Grade", "subjects.noneGrades": "No grades yet", "subjects.noneGradesCopy": "Record a score to make progress visible.", "subjects.validationName": "Please enter a subject name.", "subjects.validationGrade": "Please enter a subject for this grade.",
  "exams.title": "Exams", "exams.description": "Upcoming checkpoints, without the noise.", "exams.name": "Exam name", "exams.subject": "Subject", "exams.importance": "Importance", "exams.add": "Add", "exams.remove": "Remove", "exams.none": "No exams yet", "exams.noneCopy": "Add the next checkpoint above.", "exams.validationName": "Please enter an exam name.", "exams.validationDate": "Please choose an exam date.",
  "investment.title": "Time Investment", "investment.description": "See where your attention is actually going.", "investment.newSubject": "New investment subject", "investment.theme": "Theme", "investment.started": "Started", "investment.add": "Add", "investment.remove": "Remove", "investment.none": "No investment subjects yet", "investment.noneCopy": "Create a subject to connect timer blocks to a direction.", "investment.validation": "Please enter an investment subject name.", "theme.ocean": "Ocean", "theme.coral": "Coral", "theme.violet": "Violet", "theme.sunshine": "Sunshine", "theme.mint": "Mint",
  "mistakes.title": "Mistakes", "mistakes.description": "Review the edges where understanding can become stronger.", "mistakes.add": "+ Add mistake", "mistakes.close": "Close", "mistakes.titlePlaceholder": "Title", "mistakes.subjectPlaceholder": "Subject", "mistakes.questionPlaceholder": "What was the question?", "mistakes.reasonPlaceholder": "Why did it go wrong?", "mistakes.save": "Save mistake", "mistakes.again": "Again", "mistakes.hard": "Hard", "mistakes.gotIt": "Got it", "mistakes.mastery": "mastery", "mistakes.untitled": "Untitled mistake", "mistakes.noQuestion": "No question text recorded.", "mistakes.none": "No mistakes recorded", "mistakes.noneCopy": "That is either excellent news or a blank page. The Agent can help you capture both.", "mistakes.validation": "Please enter a mistake title.",
  "timer.title": "Study Timer", "timer.description": "Give one block of attention a clear beginning and end.", "timer.minutes": "Minutes", "timer.intensity": "Intensity", "timer.start": "Start focus block", "timer.focus": "Focus", "timer.elapsed": "{duration} elapsed", "timer.pause": "Pause", "timer.resume": "Resume", "timer.finish": "Finish", "timer.cancel": "Cancel", "timer.idle": "Idle", "timer.running": "Running", "timer.paused": "Paused", "intensity.peak": "Peak", "intensity.deepFocus": "Deep focus", "intensity.steady": "Steady", "intensity.light": "Light", "intensity.recovery": "Recovery",
  "library.title": "Library", "library.description": "The local source material your Agent can work with.", "library.add": "Add sources", "library.searchPlaceholder": "Search your library…", "library.results": "Search results", "library.line": "Line {line}", "library.noMatches": "No matches yet.", "library.empty": "Your library is empty", "library.emptyCopy": "Add a text or Markdown source to give the Agent context.",
  "agent.notebooks": "Notebooks", "agent.sources": "{count} sources", "agent.messages": "{count} messages", "agent.noNotebook": "Create a notebook to keep a thread of work together.", "agent.newNotebook": "New notebook", "agent.untitledNotebook": "Untitled Notebook {count}", "agent.promptTitle": "What are you working through?", "agent.emptyTitle": "A capable second brain, with boundaries.", "agent.emptyCopy": "Ask about a source, turn a goal into steps, or work through a hard question. Every write or execution request will ask first.", "agent.noProvider": "Connect Cloud AI or configure BYOK in Settings first.", "agent.starting": "Starting…", "agent.completed": "Completed", "agent.permission": "Permission requested", "agent.toolFallback": "The Agent wants to use a tool.", "agent.deny": "Deny", "agent.allowOnce": "Allow once", "agent.inputRequired": "The Agent needs your input", "agent.inputFallback": "What should it know?", "agent.answerPlaceholder": "Your answer", "agent.send": "Send", "agent.askPlaceholder": "Ask the Agent anything about your learning…", "agent.moreLibrary": "+{count} more in Library", "agent.shortcut": "⌘ Enter to run", "agent.cancel": "Cancel", "agent.run": "Run Agent", "agent.timeline": "Timeline", "agent.timelineDescription": "Visible work, not hidden thought.", "agent.noEvents": "Agent events will appear here as work progresses.",
  "settings.title": "Settings", "settings.description": "A few quiet controls for your local client.", "settings.appearance": "Appearance", "settings.appearanceTitle": "Make it feel like yours", "settings.theme": "Theme", "settings.themeDescription": "Use a warm light canvas or a softer dark mode.", "settings.language": "Language", "settings.languageDescription": "Choose the language used throughout StudyPulse.", "settings.provider": "Agent provider", "settings.providerTitle": "Connect when useful", "settings.providerDescription": "The local Workspace stays useful without an AI connection.", "settings.cloudConnected": "Cloud AI connected", "settings.byokConnected": "BYOK connected", "settings.notConnected": "Not connected", "settings.cloudName": "StudyPulse Cloud AI", "settings.cloudCopy": "Sign in through the secure web flow. Tokens stay in macOS Keychain.", "settings.signIn": "Sign in", "settings.working": "Working…", "settings.byokName": "BYOK · OpenAI-compatible", "settings.byokCopy": "Use your own endpoint. The key is never rendered back after saving.", "settings.baseUrl": "Base URL", "settings.model": "Model", "settings.savedKey": "Saved key · leave blank to keep", "settings.apiKey": "API key", "settings.saveByok": "Save BYOK", "settings.saving": "Saving…", "settings.disconnect": "Disconnect and remove saved credentials", "settings.privacy": "Privacy", "settings.privacyTitle": "Local-first, intentionally", "settings.privacyCopy": "Workspace records, Agent runs and Notebook history stay in the selected local directory. StudyPulse does not expose a browser localhost service.", "language.label": "Language",
  "duration.hours": "{count}h", "duration.minutes": "{count}m", "theme.light": "Light", "theme.dark": "Dark", "taskType.homework": "Homework", "taskType.reading": "Reading", "event.started": "Started", "event.statusChanged": "Status changed", "event.textDelta": "Text delta", "event.toolRequested": "Tool requested", "event.toolCompleted": "Tool completed", "event.confirmationRequired": "Confirmation required", "event.stageStarted": "Stage started", "event.stageProgress": "Stage progress", "event.stageCompleted": "Stage completed", "event.inputRequired": "Input required", "event.artifactCreated": "Artifact created", "event.failed": "Failed", "event.cancelled": "Cancelled", "event.completed": "Completed", "mode.chat": "Chat", "mode.deepSolve": "Deep solve", "mode.mastery": "Mastery", "mode.deepResearch": "Deep research", "mode.questionLab": "Question lab", "mode.visualize": "Visualize",
  "dialog.openWorkspace": "Open StudyPulse Workspace", "dialog.createWorkspace": "Create StudyPulse Workspace", "dialog.addSources": "Add Notebook Sources", "dialog.inspectBackup": "Inspect StudyPulse Backup", "dialog.exportBackup": "Export StudyPulse Backup",
};

// The base translations intentionally remain separate from P1/P2 additions so
// feature pages can be reviewed as coherent dictionary groups.
const zhCN: Record<string, string> = {
  "nav.today": "今天", "nav.agent": "Agent", "nav.tasks": "任务", "nav.subjects": "科目与成绩", "nav.exams": "考试", "nav.mistakes": "错题", "nav.timer": "学习计时器", "nav.investment": "时间投入", "nav.library": "资料库", "nav.settings": "设置", "nav.aria": "StudyPulse 分区",
  "brand.localWorkspace": "本地优先工作区", "workspace.default": "工作区", "local.stored": "储存在这台 Mac 上", "top.learningRhythm": "你的学习节奏", "top.greeting": "很高兴见到你。", "top.importBackup": "导入备份", "top.exportBackup": "导出备份", "loading.opening": "正在打开本地工作区…", "loading.failed": "StudyPulse 无法启动", "common.retry": "重试", "error.generic": "出了点问题。", "error.section": "无法加载此分区",
  "welcome.eyebrow": "安静地，一点点前进", "welcome.title": "把学习工作区留在身边。", "welcome.copy": "StudyPulse 会将数据保存在本地工作区。打开已有工作区，或创建一个新的地方来管理任务、笔记、学习记录和 Agent 工作。", "welcome.create": "创建工作区", "welcome.open": "打开工作区", "welcome.localTitle": "默认本地优先", "welcome.localCopy": "云端 AI 是可选的。你的工作区会留在这台 Mac 上。", "backup.conflicts": "有 {count} 个冲突需要检查。", "backup.ready": "备份架构 {schema} 已就绪，包含 {records} 条新记录。", "backup.applyReplace": "现在应用替换恢复吗？", "backup.exported": "备份已成功导出。",
  "today.heroTitle": "细小而持续的步伐", "today.heroEmphasis": "终会积累成改变。", "today.heroCopy": "把下一件有用的事放在手边。", "today.openTasks": "未完成任务", "today.nothingUrgent": "暂无紧急事项", "today.studyTime": "学习时长", "today.streak": "连续 {count} 天", "today.dueMistakes": "待复习错题", "today.readyReview": "可以开始复习", "today.upcomingExams": "即将考试", "today.noExamsSoon": "近期没有考试", "today.nextTitle": "接下来要做", "today.nextDescription": "短清单，也是一种体贴。", "today.general": "常规", "today.due": "截止 {date}", "today.high": "高优先级", "today.focus": "重点", "today.clearTitle": "桌面很清爽", "today.clearCopy": "想清楚下一步时，就创建一个任务。", "today.noteTitle": "今日笔记", "today.noteDescription": "温和地检查一下自己。", "today.quote": "“目标不是把一切都记在脑中，而是建立一个可以随时回来的地方。”",
  "tasks.title": "任务", "tasks.description": "为真正重要的事情保留一条可管理的队列。", "tasks.addPlaceholder": "添加任务…", "tasks.saving": "保存中…", "common.add": "添加", "tasks.noTasks": "还没有任务", "tasks.noTasksCopy": "在上方添加一个小小的下一步。", "tasks.validation": "请输入任务标题。", "subjects.title": "科目与成绩", "subjects.description": "让学业进展的轮廓清晰可见。", "subjects.subjectsTitle": "科目", "subjects.subjectsDescription": "为学习数据建立稳定的词汇。", "subjects.newSubject": "新科目", "subjects.fullScore": "满分", "subjects.addSubject": "添加科目", "subjects.active": "启用", "subjects.off": "关闭", "subjects.none": "还没有科目", "subjects.noneCopy": "添加第一个科目，开始记录成绩。", "subjects.gradesTitle": "成绩", "subjects.gradesDescription": "不用离开本地工作区，就能记录一次结果。", "subjects.examOptional": "考试名称（可选）", "subjects.score": "得分", "subjects.addGrade": "添加成绩", "subjects.grade": "成绩", "subjects.noneGrades": "还没有成绩", "subjects.noneGradesCopy": "记录一次得分，让进步变得可见。", "subjects.validationName": "请输入科目名称。", "subjects.validationGrade": "请输入这条成绩对应的科目。",
  "exams.title": "考试", "exams.description": "记录即将到来的检查点，不被噪音打扰。", "exams.name": "考试名称", "exams.subject": "科目", "exams.importance": "重要程度", "exams.add": "添加", "exams.remove": "移除", "exams.none": "还没有考试", "exams.noneCopy": "在上方添加下一个检查点。", "exams.validationName": "请输入考试名称。", "exams.validationDate": "请选择考试日期。", "investment.title": "时间投入", "investment.description": "看看你的注意力实际上流向了哪里。", "investment.newSubject": "新投入主题", "investment.theme": "主题", "investment.started": "开始于", "investment.add": "添加", "investment.remove": "移除", "investment.none": "还没有投入主题", "investment.noneCopy": "创建一个主题，把计时区块连接到明确方向。", "investment.validation": "请输入投入主题名称。", "theme.ocean": "海洋", "theme.coral": "珊瑚", "theme.violet": "紫罗兰", "theme.sunshine": "阳光", "theme.mint": "薄荷",
  "mistakes.title": "错题", "mistakes.description": "复盘理解仍可变得更扎实的地方。", "mistakes.add": "+ 添加错题", "mistakes.close": "关闭", "mistakes.titlePlaceholder": "标题", "mistakes.subjectPlaceholder": "科目", "mistakes.questionPlaceholder": "题目是什么？", "mistakes.reasonPlaceholder": "为什么会出错？", "mistakes.save": "保存错题", "mistakes.again": "再来一次", "mistakes.hard": "有点难", "mistakes.gotIt": "掌握了", "mistakes.mastery": "掌握度", "mistakes.untitled": "未命名错题", "mistakes.noQuestion": "没有记录题目内容。", "mistakes.none": "还没有错题记录", "mistakes.noneCopy": "这可能是个好消息，也可能只是空白页。Agent 可以帮你记录两者。", "mistakes.validation": "请输入错题标题。",
  "timer.title": "学习计时器", "timer.description": "为一段专注留出清晰的开始与结束。", "timer.minutes": "分钟", "timer.intensity": "专注强度", "timer.start": "开始专注", "timer.focus": "专注", "timer.elapsed": "已用时 {duration}", "timer.pause": "暂停", "timer.resume": "继续", "timer.finish": "完成", "timer.cancel": "取消", "timer.idle": "空闲", "timer.running": "进行中", "timer.paused": "已暂停", "intensity.peak": "高峰", "intensity.deepFocus": "深度专注", "intensity.steady": "稳定", "intensity.light": "轻量", "intensity.recovery": "恢复",
  "library.title": "资料库", "library.description": "Agent 可以使用的本地资料。", "library.add": "添加资料", "library.searchPlaceholder": "搜索资料库…", "library.results": "搜索结果", "library.line": "第 {line} 行", "library.noMatches": "暂时没有匹配项。", "library.empty": "资料库为空", "library.emptyCopy": "添加文本或 Markdown 资料，为 Agent 提供上下文。",
  "agent.notebooks": "笔记本", "agent.sources": "{count} 个资料", "agent.messages": "{count} 条消息", "agent.noNotebook": "创建一个笔记本，把一条工作线索集中起来。", "agent.newNotebook": "新笔记本", "agent.untitledNotebook": "未命名笔记本 {count}", "agent.promptTitle": "你正在梳理什么？", "agent.emptyTitle": "一个有边界的强大第二大脑。", "agent.emptyCopy": "询问资料、把目标拆成步骤，或一起解决难题。每次写入或执行请求都会先征求你的同意。", "agent.noProvider": "请先在设置中连接 Cloud AI 或配置 BYOK。", "agent.starting": "正在启动…", "agent.completed": "已完成", "agent.permission": "请求权限", "agent.toolFallback": "Agent 想要使用一个工具。", "agent.deny": "拒绝", "agent.allowOnce": "仅允许一次", "agent.inputRequired": "Agent 需要你的输入", "agent.inputFallback": "你希望它知道什么？", "agent.answerPlaceholder": "你的回答", "agent.send": "发送", "agent.askPlaceholder": "询问 Agent 任何与你学习有关的事…", "agent.moreLibrary": "资料库中还有 {count} 个", "agent.shortcut": "⌘ Enter 运行", "agent.cancel": "取消", "agent.run": "运行 Agent", "agent.timeline": "时间线", "agent.timelineDescription": "看得见的工作，而不是隐藏的思考。", "agent.noEvents": "Agent 的工作进展会显示在这里。",
  "settings.title": "设置", "settings.description": "为本地客户端准备的几个安静控制项。", "settings.appearance": "外观", "settings.appearanceTitle": "让它更像你的空间", "settings.theme": "主题", "settings.themeDescription": "使用温暖的浅色画布，或柔和的深色模式。", "settings.language": "语言", "settings.languageDescription": "选择 StudyPulse 全局使用的语言。", "settings.provider": "Agent 服务商", "settings.providerTitle": "需要时再连接", "settings.providerDescription": "即使没有 AI 连接，本地工作区依然有用。", "settings.cloudConnected": "Cloud AI 已连接", "settings.byokConnected": "BYOK 已连接", "settings.notConnected": "未连接", "settings.cloudName": "StudyPulse Cloud AI", "settings.cloudCopy": "通过安全网页流程登录。令牌会保存在 macOS 钥匙串中。", "settings.signIn": "登录", "settings.working": "处理中…", "settings.byokName": "BYOK · OpenAI 兼容", "settings.byokCopy": "使用你自己的端点。保存后不会再次显示密钥。", "settings.baseUrl": "基础 URL", "settings.model": "模型", "settings.savedKey": "已有密钥 · 留空以保留", "settings.apiKey": "API 密钥", "settings.saveByok": "保存 BYOK", "settings.saving": "保存中…", "settings.disconnect": "断开连接并移除已保存凭据", "settings.privacy": "隐私", "settings.privacyTitle": "刻意坚持本地优先", "settings.privacyCopy": "工作区记录、Agent 运行和笔记本历史都保存在选定的本地目录中。StudyPulse 不会暴露浏览器 localhost 服务。", "language.label": "语言",
  "duration.hours": "{count} 小时", "duration.minutes": "{count} 分钟", "theme.light": "浅色", "theme.dark": "深色", "taskType.homework": "作业", "taskType.reading": "阅读", "event.started": "已开始", "event.statusChanged": "状态变化", "event.textDelta": "文本增量", "event.toolRequested": "请求工具", "event.toolCompleted": "工具完成", "event.confirmationRequired": "需要确认", "event.stageStarted": "阶段开始", "event.stageProgress": "阶段进度", "event.stageCompleted": "阶段完成", "event.inputRequired": "需要输入", "event.artifactCreated": "已创建产物", "event.failed": "失败", "event.cancelled": "已取消", "event.completed": "已完成", "mode.chat": "聊天", "mode.deepSolve": "深度解题", "mode.mastery": "掌握训练", "mode.deepResearch": "深度研究", "mode.questionLab": "问题实验室", "mode.visualize": "可视化",
  "dialog.openWorkspace": "打开 StudyPulse 工作区", "dialog.createWorkspace": "创建 StudyPulse 工作区", "dialog.addSources": "添加笔记本资料", "dialog.inspectBackup": "检查 StudyPulse 备份", "dialog.exportBackup": "导出 StudyPulse 备份",
};

const zhTW: Record<string, string> = {
  ...zhCN,
  "nav.today": "今天", "nav.tasks": "任務", "nav.subjects": "科目與成績", "nav.exams": "考試", "nav.mistakes": "錯題", "nav.timer": "學習計時器", "nav.investment": "時間投入", "nav.library": "資料庫", "nav.settings": "設定", "nav.aria": "StudyPulse 分區", "brand.localWorkspace": "本機優先工作區", "local.stored": "儲存在這台 Mac 上", "top.learningRhythm": "你的學習節奏", "top.greeting": "很高興見到你。", "top.importBackup": "匯入備份", "top.exportBackup": "匯出備份", "loading.opening": "正在開啟本機工作區…", "loading.failed": "StudyPulse 無法啟動", "common.retry": "重試", "error.generic": "出了點問題。", "error.section": "無法載入此分區", "welcome.eyebrow": "安靜地，一點點前進", "welcome.title": "把學習工作區留在身邊。", "welcome.copy": "StudyPulse 會將資料儲存在本機工作區。開啟既有工作區，或建立新的地方來管理任務、筆記、學習記錄和 Agent 工作。", "welcome.create": "建立工作區", "welcome.open": "開啟工作區", "welcome.localTitle": "預設本機優先", "welcome.localCopy": "雲端 AI 是選用的。你的工作區會留在這台 Mac 上。", "backup.conflicts": "有 {count} 個衝突需要檢查。", "backup.ready": "備份架構 {schema} 已就緒，包含 {records} 筆新記錄。", "backup.applyReplace": "現在套用取代還原嗎？", "backup.exported": "備份已成功匯出。",
  "today.heroTitle": "細小而持續的步伐", "today.heroEmphasis": "終會累積成改變。", "today.heroCopy": "把下一件有用的事放在手邊。", "today.openTasks": "未完成任務", "today.nothingUrgent": "暫無緊急事項", "today.studyTime": "學習時長", "today.streak": "連續 {count} 天", "today.dueMistakes": "待複習錯題", "today.readyReview": "可以開始複習", "today.upcomingExams": "即將考試", "today.noExamsSoon": "近期沒有考試", "today.nextTitle": "接下來要做", "today.nextDescription": "短清單，也是一種體貼。", "today.general": "一般", "today.due": "截止 {date}", "today.high": "高優先級", "today.focus": "重點", "today.clearTitle": "桌面很清爽", "today.clearCopy": "想清楚下一步時，就建立一個任務。", "today.noteTitle": "今日筆記", "today.noteDescription": "溫和地檢查一下自己。", "today.quote": "「目標不是把一切都記在腦中，而是建立一個可以隨時回來的地方。」",
  "tasks.title": "任務", "tasks.description": "為真正重要的事情保留一條可管理的佇列。", "tasks.addPlaceholder": "新增任務…", "tasks.saving": "儲存中…", "common.add": "新增", "tasks.noTasks": "還沒有任務", "tasks.noTasksCopy": "在上方新增一個小小的下一步。", "tasks.validation": "請輸入任務標題。", "subjects.title": "科目與成績", "subjects.description": "讓學業進展的輪廓清晰可見。", "subjects.subjectsTitle": "科目", "subjects.subjectsDescription": "為學習資料建立穩定的詞彙。", "subjects.newSubject": "新科目", "subjects.fullScore": "滿分", "subjects.addSubject": "新增科目", "subjects.active": "啟用", "subjects.off": "關閉", "subjects.none": "還沒有科目", "subjects.noneCopy": "新增第一個科目，開始記錄成績。", "subjects.gradesTitle": "成績", "subjects.gradesDescription": "不用離開本機工作區，就能記錄一次結果。", "subjects.examOptional": "考試名稱（選填）", "subjects.score": "得分", "subjects.addGrade": "新增成績", "subjects.grade": "成績", "subjects.noneGrades": "還沒有成績", "subjects.noneGradesCopy": "記錄一次得分，讓進步變得可見。", "subjects.validationName": "請輸入科目名稱。", "subjects.validationGrade": "請輸入這筆成績對應的科目。",
  "exams.title": "考試", "exams.description": "記錄即將到來的檢查點，不被雜訊打擾。", "exams.name": "考試名稱", "exams.subject": "科目", "exams.importance": "重要程度", "exams.add": "新增", "exams.remove": "移除", "exams.none": "還沒有考試", "exams.noneCopy": "在上方新增下一個檢查點。", "exams.validationName": "請輸入考試名稱。", "exams.validationDate": "請選擇考試日期。", "investment.title": "時間投入", "investment.description": "看看你的注意力實際流向了哪裡。", "investment.newSubject": "新投入主題", "investment.theme": "主題", "investment.started": "開始於", "investment.add": "新增", "investment.remove": "移除", "investment.none": "還沒有投入主題", "investment.noneCopy": "建立一個主題，把計時區塊連接到明確方向。", "investment.validation": "請輸入投入主題名稱。", "theme.ocean": "海洋", "theme.coral": "珊瑚", "theme.violet": "紫羅蘭", "theme.sunshine": "陽光", "theme.mint": "薄荷",
  "mistakes.title": "錯題", "mistakes.description": "複習理解仍可變得更紮實的地方。", "mistakes.add": "+ 新增錯題", "mistakes.close": "關閉", "mistakes.titlePlaceholder": "標題", "mistakes.subjectPlaceholder": "科目", "mistakes.questionPlaceholder": "題目是什麼？", "mistakes.reasonPlaceholder": "為什麼會出錯？", "mistakes.save": "儲存錯題", "mistakes.again": "再來一次", "mistakes.hard": "有點難", "mistakes.gotIt": "掌握了", "mistakes.mastery": "掌握度", "mistakes.untitled": "未命名錯題", "mistakes.noQuestion": "沒有記錄題目內容。", "mistakes.none": "還沒有錯題記錄", "mistakes.noneCopy": "這可能是個好消息，也可能只是空白頁。Agent 可以幫你記錄兩者。", "mistakes.validation": "請輸入錯題標題。",
  "timer.title": "學習計時器", "timer.description": "為一段專注留出清晰的開始與結束。", "timer.minutes": "分鐘", "timer.intensity": "專注強度", "timer.start": "開始專注", "timer.focus": "專注", "timer.elapsed": "已用時 {duration}", "timer.pause": "暫停", "timer.resume": "繼續", "timer.finish": "完成", "timer.cancel": "取消", "timer.idle": "閒置", "timer.running": "進行中", "timer.paused": "已暫停", "intensity.peak": "高峰", "intensity.deepFocus": "深度專注", "intensity.steady": "穩定", "intensity.light": "輕量", "intensity.recovery": "恢復",
  "library.title": "資料庫", "library.description": "Agent 可以使用的本機資料。", "library.add": "新增資料", "library.searchPlaceholder": "搜尋資料庫…", "library.results": "搜尋結果", "library.line": "第 {line} 行", "library.noMatches": "暫時沒有符合項目。", "library.empty": "資料庫是空的", "library.emptyCopy": "新增文字或 Markdown 資料，為 Agent 提供上下文。",
  "agent.notebooks": "筆記本", "agent.sources": "{count} 個資料", "agent.messages": "{count} 則訊息", "agent.noNotebook": "建立一個筆記本，把一條工作線索集中起來。", "agent.newNotebook": "新筆記本", "agent.untitledNotebook": "未命名筆記本 {count}", "agent.promptTitle": "你正在梳理什麼？", "agent.emptyTitle": "一個有邊界的強大第二大腦。", "agent.emptyCopy": "詢問資料、把目標拆成步驟，或一起解決難題。每次寫入或執行請求都會先徵求你的同意。", "agent.noProvider": "請先在設定中連接 Cloud AI 或設定 BYOK。", "agent.starting": "正在啟動…", "agent.completed": "已完成", "agent.permission": "請求權限", "agent.toolFallback": "Agent 想要使用一個工具。", "agent.deny": "拒絕", "agent.allowOnce": "僅允許一次", "agent.inputRequired": "Agent 需要你的輸入", "agent.inputFallback": "你希望它知道什麼？", "agent.answerPlaceholder": "你的回答", "agent.send": "傳送", "agent.askPlaceholder": "詢問 Agent 任何與學習有關的事…", "agent.moreLibrary": "資料庫中還有 {count} 個", "agent.shortcut": "⌘ Enter 執行", "agent.cancel": "取消", "agent.run": "執行 Agent", "agent.timeline": "時間線", "agent.timelineDescription": "看得見的工作，而不是隱藏的思考。", "agent.noEvents": "Agent 的工作進展會顯示在這裡。",
  "settings.title": "設定", "settings.description": "為本機用戶端準備的幾個安靜控制項。", "settings.appearance": "外觀", "settings.appearanceTitle": "讓它更像你的空間", "settings.theme": "主題", "settings.themeDescription": "使用溫暖的淺色畫布，或柔和的深色模式。", "settings.language": "語言", "settings.languageDescription": "選擇 StudyPulse 全域使用的語言。", "settings.provider": "Agent 服務商", "settings.providerTitle": "需要時再連接", "settings.providerDescription": "即使沒有 AI 連接，本機工作區依然有用。", "settings.cloudConnected": "Cloud AI 已連接", "settings.byokConnected": "BYOK 已連接", "settings.notConnected": "未連接", "settings.cloudName": "StudyPulse Cloud AI", "settings.cloudCopy": "透過安全網頁流程登入。權杖會儲存在 macOS 鑰匙圈中。", "settings.signIn": "登入", "settings.working": "處理中…", "settings.byokName": "BYOK · OpenAI 相容", "settings.byokCopy": "使用你自己的端點。儲存後不會再次顯示金鑰。", "settings.baseUrl": "基礎 URL", "settings.model": "模型", "settings.savedKey": "已有金鑰 · 留空以保留", "settings.apiKey": "API 金鑰", "settings.saveByok": "儲存 BYOK", "settings.saving": "儲存中…", "settings.disconnect": "中斷連接並移除已儲存憑據", "settings.privacy": "隱私", "settings.privacyTitle": "刻意堅持本機優先", "settings.privacyCopy": "工作區記錄、Agent 執行和筆記本歷史都保存在選定的本機目錄中。StudyPulse 不會暴露瀏覽器 localhost 服務。", "language.label": "語言", "duration.hours": "{count} 小時", "duration.minutes": "{count} 分鐘", "taskType.homework": "作業", "taskType.reading": "閱讀", "event.started": "已開始", "event.statusChanged": "狀態變化", "event.textDelta": "文字增量", "event.toolRequested": "請求工具", "event.toolCompleted": "工具完成", "event.confirmationRequired": "需要確認", "event.stageStarted": "階段開始", "event.stageProgress": "階段進度", "event.stageCompleted": "階段完成", "event.inputRequired": "需要輸入", "event.artifactCreated": "已建立產物", "event.failed": "失敗", "event.cancelled": "已取消", "event.completed": "已完成", "mode.chat": "聊天", "mode.deepSolve": "深度解題", "mode.mastery": "掌握訓練", "mode.deepResearch": "深度研究", "mode.questionLab": "問題實驗室", "mode.visualize": "視覺化", "dialog.openWorkspace": "開啟 StudyPulse 工作區", "dialog.createWorkspace": "建立 StudyPulse 工作區", "dialog.addSources": "新增筆記本資料", "dialog.inspectBackup": "檢查 StudyPulse 備份", "dialog.exportBackup": "匯出 StudyPulse 備份",
};

const ja: Record<string, string> = {
  "nav.today": "今日", "nav.agent": "Agent", "nav.tasks": "タスク", "nav.subjects": "科目と成績", "nav.exams": "試験", "nav.mistakes": "間違い", "nav.timer": "学習タイマー", "nav.investment": "時間投資", "nav.library": "ライブラリ", "nav.settings": "設定", "nav.aria": "StudyPulse セクション", "brand.localWorkspace": "ローカル優先ワークスペース", "workspace.default": "ワークスペース", "local.stored": "この Mac に保存", "top.learningRhythm": "あなたの学習リズム", "top.greeting": "会えてうれしいです。", "top.importBackup": "バックアップを読み込む", "top.exportBackup": "バックアップを書き出す", "loading.opening": "ローカルワークスペースを開いています…", "loading.failed": "StudyPulse を起動できませんでした", "common.retry": "再試行", "error.generic": "問題が発生しました。", "error.section": "このセクションを読み込めませんでした",
  "welcome.eyebrow": "静かに、少しずつ前へ", "welcome.title": "学習ワークスペースを、すぐそばに。", "welcome.copy": "StudyPulse はデータをローカルのワークスペースに保存します。既存のワークスペースを開くか、タスク、ノート、セッション、Agent の作業場所を新しく作成できます。", "welcome.create": "ワークスペースを作成", "welcome.open": "ワークスペースを開く", "welcome.localTitle": "デフォルトでローカル優先", "welcome.localCopy": "Cloud AI は任意です。ワークスペースはこの Mac に残ります。", "backup.conflicts": "確認が必要な競合が {count} 件あります。", "backup.ready": "バックアップスキーマ {schema} の準備ができました。新しいレコードは {records} 件です。", "backup.applyReplace": "今すぐ置換復元を適用しますか？", "backup.exported": "バックアップを書き出しました。",
  "today.heroTitle": "小さく、続ける一歩", "today.heroEmphasis": "積み重なります。", "today.heroCopy": "次に役立つことを、すぐそばに。", "today.openTasks": "未完了タスク", "today.nothingUrgent": "急ぎのものはありません", "today.studyTime": "学習時間", "today.streak": "{count}日連続", "today.dueMistakes": "復習する間違い", "today.readyReview": "復習の準備ができています", "today.upcomingExams": "今後の試験", "today.noExamsSoon": "近い試験はありません", "today.nextTitle": "次に取り組むこと", "today.nextDescription": "短いリストは、やさしいリストです。", "today.general": "一般", "today.due": "期限 {date}", "today.high": "高", "today.focus": "集中", "today.clearTitle": "やることはありません", "today.clearCopy": "次にやることが見えたら、タスクを作りましょう。", "today.noteTitle": "今日のメモ", "today.noteDescription": "やさしく振り返りましょう。", "today.quote": "「すべてを頭の中に抱えることが目標ではない。戻ってこられる場所を作ることが目標だ。」",
  "tasks.title": "タスク", "tasks.description": "大切なことのための、管理しやすいキュー。", "tasks.addPlaceholder": "タスクを追加…", "tasks.saving": "保存中…", "common.add": "追加", "tasks.noTasks": "タスクはまだありません", "tasks.noTasksCopy": "上に小さな次の一歩を追加しましょう。", "tasks.validation": "タスクのタイトルを入力してください。", "subjects.title": "科目と成績", "subjects.description": "学習の進み方を見える形に保ちます。", "subjects.subjectsTitle": "科目", "subjects.subjectsDescription": "学習データのための安定した語彙。", "subjects.newSubject": "新しい科目", "subjects.fullScore": "満点", "subjects.addSubject": "科目を追加", "subjects.active": "有効", "subjects.off": "オフ", "subjects.none": "科目はまだありません", "subjects.noneCopy": "最初の科目を追加して成績を記録しましょう。", "subjects.gradesTitle": "成績", "subjects.gradesDescription": "ローカルワークスペースを離れずに結果を記録できます。", "subjects.examOptional": "試験名（任意）", "subjects.score": "得点", "subjects.addGrade": "成績を追加", "subjects.grade": "成績", "subjects.noneGrades": "成績はまだありません", "subjects.noneGradesCopy": "得点を記録して進歩を見えるようにしましょう。", "subjects.validationName": "科目名を入力してください。", "subjects.validationGrade": "この成績の科目を入力してください。",
  "exams.title": "試験", "exams.description": "ノイズを減らして、これからのチェックポイントを管理。", "exams.name": "試験名", "exams.subject": "科目", "exams.importance": "重要度", "exams.add": "追加", "exams.remove": "削除", "exams.none": "試験はまだありません", "exams.noneCopy": "上に次のチェックポイントを追加しましょう。", "exams.validationName": "試験名を入力してください。", "exams.validationDate": "試験日を選択してください。", "investment.title": "時間投資", "investment.description": "あなたの注意が実際にどこへ向かっているかを確認。", "investment.newSubject": "新しい投資対象", "investment.theme": "テーマ", "investment.started": "開始日", "investment.add": "追加", "investment.remove": "削除", "investment.none": "投資対象はまだありません", "investment.noneCopy": "対象を作成してタイマーブロックを方向づけましょう。", "investment.validation": "投資対象名を入力してください。", "theme.ocean": "オーシャン", "theme.coral": "コーラル", "theme.violet": "バイオレット", "theme.sunshine": "サンシャイン", "theme.mint": "ミント",
  "mistakes.title": "間違い", "mistakes.description": "理解をさらに強くできる箇所を復習します。", "mistakes.add": "+ 間違いを追加", "mistakes.close": "閉じる", "mistakes.titlePlaceholder": "タイトル", "mistakes.subjectPlaceholder": "科目", "mistakes.questionPlaceholder": "問題は何でしたか？", "mistakes.reasonPlaceholder": "なぜ間違えましたか？", "mistakes.save": "間違いを保存", "mistakes.again": "もう一度", "mistakes.hard": "難しい", "mistakes.gotIt": "わかった", "mistakes.mastery": "習熟度", "mistakes.untitled": "名前のない間違い", "mistakes.noQuestion": "問題文は記録されていません。", "mistakes.none": "間違いは記録されていません", "mistakes.noneCopy": "すばらしい知らせか、空白のページかもしれません。Agent はどちらも記録できます。", "mistakes.validation": "間違いのタイトルを入力してください。",
  "timer.title": "学習タイマー", "timer.description": "集中の一ブロックに、はっきりした始まりと終わりを。", "timer.minutes": "分", "timer.intensity": "強度", "timer.start": "集中ブロックを開始", "timer.focus": "集中", "timer.elapsed": "経過 {duration}", "timer.pause": "一時停止", "timer.resume": "再開", "timer.finish": "完了", "timer.cancel": "キャンセル", "timer.idle": "待機中", "timer.running": "実行中", "timer.paused": "一時停止中", "intensity.peak": "ピーク", "intensity.deepFocus": "深い集中", "intensity.steady": "安定", "intensity.light": "軽め", "intensity.recovery": "回復",
  "library.title": "ライブラリ", "library.description": "Agent が扱えるローカルの資料。", "library.add": "資料を追加", "library.searchPlaceholder": "ライブラリを検索…", "library.results": "検索結果", "library.line": "{line} 行目", "library.noMatches": "一致するものはありません。", "library.empty": "ライブラリは空です", "library.emptyCopy": "テキストまたは Markdown の資料を追加して Agent に文脈を与えましょう。",
  "agent.notebooks": "ノートブック", "agent.sources": "資料 {count} 件", "agent.messages": "メッセージ {count} 件", "agent.noNotebook": "ノートブックを作成して作業の流れをまとめましょう。", "agent.newNotebook": "新しいノートブック", "agent.untitledNotebook": "名前のないノートブック {count}", "agent.promptTitle": "何について考えていますか？", "agent.emptyTitle": "境界線を持つ、頼れる第二の脳。", "agent.emptyCopy": "資料について尋ねたり、目標を手順にしたり、難しい問いを一緒に考えたりできます。書き込みや実行の前には必ず確認します。", "agent.noProvider": "まず設定で Cloud AI に接続するか BYOK を設定してください。", "agent.starting": "開始中…", "agent.completed": "完了", "agent.permission": "権限のリクエスト", "agent.toolFallback": "Agent がツールを使おうとしています。", "agent.deny": "拒否", "agent.allowOnce": "今回のみ許可", "agent.inputRequired": "Agent に入力が必要です", "agent.inputFallback": "何を知る必要がありますか？", "agent.answerPlaceholder": "回答", "agent.send": "送信", "agent.askPlaceholder": "学習について Agent に何でも尋ねてください…", "agent.moreLibrary": "ライブラリに他 {count} 件", "agent.shortcut": "⌘ Enter で実行", "agent.cancel": "キャンセル", "agent.run": "Agent を実行", "agent.timeline": "タイムライン", "agent.timelineDescription": "隠れた思考ではなく、見える作業。", "agent.noEvents": "Agent の進行状況がここに表示されます。",
  "settings.title": "設定", "settings.description": "ローカルクライアントのための、静かなコントロール。", "settings.appearance": "外観", "settings.appearanceTitle": "自分らしく整える", "settings.theme": "テーマ", "settings.themeDescription": "温かいライトキャンバス、または柔らかなダークモードを使います。", "settings.language": "言語", "settings.languageDescription": "StudyPulse 全体で使う言語を選択します。", "settings.provider": "Agent プロバイダー", "settings.providerTitle": "必要なときに接続", "settings.providerDescription": "AI に接続しなくてもローカルワークスペースは役立ちます。", "settings.cloudConnected": "Cloud AI 接続済み", "settings.byokConnected": "BYOK 接続済み", "settings.notConnected": "未接続", "settings.cloudName": "StudyPulse Cloud AI", "settings.cloudCopy": "安全なウェブフローでサインインします。トークンは macOS キーチェーンに保存されます。", "settings.signIn": "サインイン", "settings.working": "処理中…", "settings.byokName": "BYOK · OpenAI 互換", "settings.byokCopy": "自分のエンドポイントを使用します。保存後にキーが再表示されることはありません。", "settings.baseUrl": "ベース URL", "settings.model": "モデル", "settings.savedKey": "保存済みキー · 保持する場合は空欄", "settings.apiKey": "API キー", "settings.saveByok": "BYOK を保存", "settings.saving": "保存中…", "settings.disconnect": "接続を解除して保存済み認証情報を削除", "settings.privacy": "プライバシー", "settings.privacyTitle": "意図的にローカル優先", "settings.privacyCopy": "ワークスペースの記録、Agent の実行、ノートブック履歴は選択したローカルディレクトリに残ります。StudyPulse はブラウザー向け localhost サービスを公開しません。", "language.label": "言語", "duration.hours": "{count}時間", "duration.minutes": "{count}分", "theme.light": "ライト", "theme.dark": "ダーク", "taskType.homework": "宿題", "taskType.reading": "読書", "event.started": "開始", "event.statusChanged": "状態変更", "event.textDelta": "テキスト差分", "event.toolRequested": "ツールをリクエスト", "event.toolCompleted": "ツール完了", "event.confirmationRequired": "確認が必要", "event.stageStarted": "ステージ開始", "event.stageProgress": "ステージ進行", "event.stageCompleted": "ステージ完了", "event.inputRequired": "入力が必要", "event.artifactCreated": "成果物を作成", "event.failed": "失敗", "event.cancelled": "キャンセル済み", "event.completed": "完了", "mode.chat": "チャット", "mode.deepSolve": "深い問題解決", "mode.mastery": "習熟", "mode.deepResearch": "深い調査", "mode.questionLab": "質問ラボ", "mode.visualize": "可視化", "dialog.openWorkspace": "StudyPulse ワークスペースを開く", "dialog.createWorkspace": "StudyPulse ワークスペースを作成", "dialog.addSources": "ノートブック資料を追加", "dialog.inspectBackup": "StudyPulse バックアップを確認", "dialog.exportBackup": "StudyPulse バックアップを書き出す",
};

const ko: Record<string, string> = {
  "nav.today": "오늘", "nav.agent": "Agent", "nav.tasks": "할 일", "nav.subjects": "과목 및 성적", "nav.exams": "시험", "nav.mistakes": "오답", "nav.timer": "학습 타이머", "nav.investment": "시간 투자", "nav.library": "라이브러리", "nav.settings": "설정", "nav.aria": "StudyPulse 섹션", "brand.localWorkspace": "로컬 우선 워크스페이스", "workspace.default": "워크스페이스", "local.stored": "이 Mac에 저장됨", "top.learningRhythm": "나의 학습 리듬", "top.greeting": "다시 만나 반가워요.", "top.importBackup": "백업 가져오기", "top.exportBackup": "백업 내보내기", "loading.opening": "로컬 워크스페이스를 여는 중…", "loading.failed": "StudyPulse를 시작할 수 없습니다", "common.retry": "다시 시도", "error.generic": "문제가 발생했습니다.", "error.section": "이 섹션을 불러올 수 없습니다",
  "welcome.eyebrow": "조용히, 한 걸음씩 나아가는 곳", "welcome.title": "학습 워크스페이스를 가까이에.", "welcome.copy": "StudyPulse는 데이터를 로컬 워크스페이스에 보관합니다. 기존 워크스페이스를 열거나 할 일, 노트, 세션, Agent 작업을 위한 새 공간을 만들 수 있습니다.", "welcome.create": "워크스페이스 만들기", "welcome.open": "워크스페이스 열기", "welcome.localTitle": "기본은 로컬 우선", "welcome.localCopy": "Cloud AI는 선택 사항입니다. 워크스페이스는 이 Mac에 보관됩니다.", "backup.conflicts": "검토가 필요한 충돌이 {count}개 있습니다.", "backup.ready": "백업 스키마 {schema}가 준비되었습니다. 새 레코드는 {records}개입니다.", "backup.applyReplace": "지금 교체 복원을 적용할까요?", "backup.exported": "백업을 내보냈습니다.",
  "today.heroTitle": "작고 꾸준한 걸음이", "today.heroEmphasis": "변화를 만듭니다.", "today.heroCopy": "다음에 유용한 일을 가까이에 두세요.", "today.openTasks": "미완료 할 일", "today.nothingUrgent": "급한 일이 없습니다", "today.studyTime": "학습 시간", "today.streak": "{count}일 연속", "today.dueMistakes": "복습할 오답", "today.readyReview": "복습할 준비가 됐어요", "today.upcomingExams": "다가오는 시험", "today.noExamsSoon": "가까운 시험이 없습니다", "today.nextTitle": "다음 할 일", "today.nextDescription": "짧은 목록은 다정한 목록입니다.", "today.general": "일반", "today.due": "마감 {date}", "today.high": "높음", "today.focus": "집중", "today.clearTitle": "책상이 비어 있어요", "today.clearCopy": "다음 일이 분명해지면 할 일을 하나 만들어 보세요.", "today.noteTitle": "오늘의 메모", "today.noteDescription": "부드럽게 돌아보세요.", "today.quote": "“모든 것을 머릿속에 담는 것이 목표가 아닙니다. 다시 돌아올 수 있는 곳을 만드는 것이 목표입니다.”",
  "tasks.title": "할 일", "tasks.description": "중요한 일을 위한 관리 가능한 대기열입니다.", "tasks.addPlaceholder": "할 일 추가…", "tasks.saving": "저장 중…", "common.add": "추가", "tasks.noTasks": "아직 할 일이 없습니다", "tasks.noTasksCopy": "위에 작은 다음 단계를 추가해 보세요.", "tasks.validation": "할 일 제목을 입력하세요.", "subjects.title": "과목 및 성적", "subjects.description": "학업의 흐름을 눈에 보이게 유지하세요.", "subjects.subjectsTitle": "과목", "subjects.subjectsDescription": "학습 데이터를 위한 일관된 용어입니다.", "subjects.newSubject": "새 과목", "subjects.fullScore": "만점", "subjects.addSubject": "과목 추가", "subjects.active": "활성", "subjects.off": "끔", "subjects.none": "아직 과목이 없습니다", "subjects.noneCopy": "첫 과목을 추가해 성적 기록을 시작하세요.", "subjects.gradesTitle": "성적", "subjects.gradesDescription": "로컬 워크스페이스를 떠나지 않고 결과를 기록하세요.", "subjects.examOptional": "시험 이름(선택)", "subjects.score": "점수", "subjects.addGrade": "성적 추가", "subjects.grade": "성적", "subjects.noneGrades": "아직 성적이 없습니다", "subjects.noneGradesCopy": "점수를 기록해 성장을 보이게 만들어 보세요.", "subjects.validationName": "과목 이름을 입력하세요.", "subjects.validationGrade": "이 성적의 과목을 입력하세요.",
  "exams.title": "시험", "exams.description": "소음 없이 다가오는 체크포인트를 관리하세요.", "exams.name": "시험 이름", "exams.subject": "과목", "exams.importance": "중요도", "exams.add": "추가", "exams.remove": "삭제", "exams.none": "아직 시험이 없습니다", "exams.noneCopy": "위에 다음 체크포인트를 추가하세요.", "exams.validationName": "시험 이름을 입력하세요.", "exams.validationDate": "시험 날짜를 선택하세요.", "investment.title": "시간 투자", "investment.description": "주의가 실제로 어디로 향하는지 확인하세요.", "investment.newSubject": "새 투자 주제", "investment.theme": "테마", "investment.started": "시작일", "investment.add": "추가", "investment.remove": "삭제", "investment.none": "아직 투자 주제가 없습니다", "investment.noneCopy": "주제를 만들어 타이머 블록의 방향을 연결하세요.", "investment.validation": "투자 주제 이름을 입력하세요.", "theme.ocean": "바다", "theme.coral": "코랄", "theme.violet": "바이올렛", "theme.sunshine": "햇살", "theme.mint": "민트",
  "mistakes.title": "오답", "mistakes.description": "이해를 더 단단하게 만들 수 있는 지점을 복습하세요.", "mistakes.add": "+ 오답 추가", "mistakes.close": "닫기", "mistakes.titlePlaceholder": "제목", "mistakes.subjectPlaceholder": "과목", "mistakes.questionPlaceholder": "문제가 무엇이었나요?", "mistakes.reasonPlaceholder": "왜 틀렸나요?", "mistakes.save": "오답 저장", "mistakes.again": "다시", "mistakes.hard": "어려움", "mistakes.gotIt": "알겠어요", "mistakes.mastery": "숙달도", "mistakes.untitled": "제목 없는 오답", "mistakes.noQuestion": "기록된 문제 내용이 없습니다.", "mistakes.none": "기록된 오답이 없습니다", "mistakes.noneCopy": "아주 좋은 소식이거나 빈 페이지일 수 있습니다. Agent가 둘 다 기록하도록 도와줄 수 있어요.", "mistakes.validation": "오답 제목을 입력하세요.",
  "timer.title": "학습 타이머", "timer.description": "집중 한 블록의 시작과 끝을 분명하게 정하세요.", "timer.minutes": "분", "timer.intensity": "집중 강도", "timer.start": "집중 블록 시작", "timer.focus": "집중", "timer.elapsed": "경과 {duration}", "timer.pause": "일시정지", "timer.resume": "재개", "timer.finish": "완료", "timer.cancel": "취소", "timer.idle": "대기", "timer.running": "진행 중", "timer.paused": "일시정지됨", "intensity.peak": "최고", "intensity.deepFocus": "깊은 집중", "intensity.steady": "꾸준히", "intensity.light": "가볍게", "intensity.recovery": "회복",
  "library.title": "라이브러리", "library.description": "Agent가 활용할 수 있는 로컬 자료입니다.", "library.add": "자료 추가", "library.searchPlaceholder": "라이브러리 검색…", "library.results": "검색 결과", "library.line": "{line}번째 줄", "library.noMatches": "일치하는 항목이 없습니다.", "library.empty": "라이브러리가 비어 있습니다", "library.emptyCopy": "텍스트 또는 Markdown 자료를 추가해 Agent에 맥락을 제공하세요.",
  "agent.notebooks": "노트북", "agent.sources": "자료 {count}개", "agent.messages": "메시지 {count}개", "agent.noNotebook": "노트북을 만들어 작업 흐름을 한곳에 모아 보세요.", "agent.newNotebook": "새 노트북", "agent.untitledNotebook": "제목 없는 노트북 {count}", "agent.promptTitle": "무엇을 고민하고 있나요?", "agent.emptyTitle": "경계를 지키는 유능한 두 번째 두뇌.", "agent.emptyCopy": "자료에 대해 묻고, 목표를 단계로 나누고, 어려운 질문을 함께 풀어 보세요. 쓰기나 실행 요청은 항상 먼저 확인합니다.", "agent.noProvider": "먼저 설정에서 Cloud AI에 연결하거나 BYOK를 구성하세요.", "agent.starting": "시작 중…", "agent.completed": "완료", "agent.permission": "권한 요청", "agent.toolFallback": "Agent가 도구를 사용하려고 합니다.", "agent.deny": "거부", "agent.allowOnce": "한 번 허용", "agent.inputRequired": "Agent에 입력이 필요합니다", "agent.inputFallback": "무엇을 알아야 할까요?", "agent.answerPlaceholder": "답변", "agent.send": "보내기", "agent.askPlaceholder": "학습에 관해 Agent에게 무엇이든 물어보세요…", "agent.moreLibrary": "라이브러리에 {count}개 더 있음", "agent.shortcut": "⌘ Enter로 실행", "agent.cancel": "취소", "agent.run": "Agent 실행", "agent.timeline": "타임라인", "agent.timelineDescription": "숨겨진 생각이 아닌, 보이는 작업입니다.", "agent.noEvents": "Agent의 진행 상황이 여기에 표시됩니다.",
  "settings.title": "설정", "settings.description": "로컬 클라이언트를 위한 조용한 제어 항목입니다.", "settings.appearance": "모양", "settings.appearanceTitle": "나만의 공간으로 만들기", "settings.theme": "테마", "settings.themeDescription": "따뜻한 라이트 캔버스나 부드러운 다크 모드를 사용하세요.", "settings.language": "언어", "settings.languageDescription": "StudyPulse 전체에서 사용할 언어를 선택하세요.", "settings.provider": "Agent 제공자", "settings.providerTitle": "필요할 때 연결", "settings.providerDescription": "AI에 연결하지 않아도 로컬 워크스페이스는 유용합니다.", "settings.cloudConnected": "Cloud AI 연결됨", "settings.byokConnected": "BYOK 연결됨", "settings.notConnected": "연결 안 됨", "settings.cloudName": "StudyPulse Cloud AI", "settings.cloudCopy": "안전한 웹 흐름으로 로그인합니다. 토큰은 macOS 키체인에 보관됩니다.", "settings.signIn": "로그인", "settings.working": "처리 중…", "settings.byokName": "BYOK · OpenAI 호환", "settings.byokCopy": "자신의 엔드포인트를 사용하세요. 저장 후 키는 다시 표시되지 않습니다.", "settings.baseUrl": "기본 URL", "settings.model": "모델", "settings.savedKey": "저장된 키 · 유지하려면 비워 두세요", "settings.apiKey": "API 키", "settings.saveByok": "BYOK 저장", "settings.saving": "저장 중…", "settings.disconnect": "연결 해제 및 저장된 자격 증명 제거", "settings.privacy": "개인정보 보호", "settings.privacyTitle": "의도적으로 로컬 우선", "settings.privacyCopy": "워크스페이스 기록, Agent 실행, 노트북 기록은 선택한 로컬 디렉터리에 남습니다. StudyPulse는 브라우저 localhost 서비스를 노출하지 않습니다.", "language.label": "언어", "duration.hours": "{count}시간", "duration.minutes": "{count}분", "theme.light": "라이트", "theme.dark": "다크", "taskType.homework": "숙제", "taskType.reading": "읽기", "event.started": "시작됨", "event.statusChanged": "상태 변경", "event.textDelta": "텍스트 변경", "event.toolRequested": "도구 요청", "event.toolCompleted": "도구 완료", "event.confirmationRequired": "확인 필요", "event.stageStarted": "단계 시작", "event.stageProgress": "단계 진행", "event.stageCompleted": "단계 완료", "event.inputRequired": "입력 필요", "event.artifactCreated": "결과물 생성", "event.failed": "실패", "event.cancelled": "취소됨", "event.completed": "완료", "mode.chat": "채팅", "mode.deepSolve": "심층 풀이", "mode.mastery": "숙달", "mode.deepResearch": "심층 조사", "mode.questionLab": "질문 연구실", "mode.visualize": "시각화", "dialog.openWorkspace": "StudyPulse 워크스페이스 열기", "dialog.createWorkspace": "StudyPulse 워크스페이스 만들기", "dialog.addSources": "노트북 자료 추가", "dialog.inspectBackup": "StudyPulse 백업 검사", "dialog.exportBackup": "StudyPulse 백업 내보내기",
};

// P1 keys belong to Diary, Trends, and Flashcards. They are merged after base
// dictionaries so feature-specific wording can override a shared key.
const p1En: Record<string, string> = {
  "nav.diary": "Diary", "nav.trends": "Trends", "nav.flashcards": "Flashcards",
  "diary.title": "Learning Diary", "diary.description": "A small daily record for mood, energy and what you learned.", "diary.new": "New entry", "diary.edit": "Edit entry", "diary.entryTitle": "Daily check-in", "diary.entryDescription": "Multiple entries on the same day are supported.", "diary.date": "Date", "diary.mood": "Mood", "diary.energy": "Energy", "diary.tag": "Energy tag", "diary.tagPlaceholder": "e.g. focused, tired", "diary.content": "Markdown note", "diary.contentPlaceholder": "What happened today?", "diary.update": "Update entry", "diary.save": "Save entry", "diary.cancel": "Cancel", "diary.trendTitle": "Recent rhythm", "diary.trendDescription": "Your daily mood and energy over the last 30 days.", "diary.activeDays": "active days", "diary.studyMinutes": "study minutes", "diary.energyShort": "energy", "diary.history": "Diary history", "diary.historyDescription": "Your entries, kept local and easy to revisit.", "diary.delete": "Delete", "diary.noContent": "No note content.", "diary.empty": "No diary entries yet", "diary.emptyCopy": "Start with a quick mood and a sentence about today.", "diary.validationDate": "Please choose a date.", "diary.confirmDelete": "Delete this diary entry?",
  "trends.title": "Trends", "trends.description": "See how study time, results, wellbeing and review connect.", "trends.score": "Score", "trends.ranking": "Ranking", "trends.heatmapTitle": "90-day activity", "trends.heatmapDescription": "Study minutes + reviews + grades × 5.", "trends.activeDays": "active days", "trends.points": "activity points", "trends.streak": "day streak", "trends.studyTime": "study time", "trends.range": "{start} – {end}", "trends.averageMood": "Average mood", "trends.averageEnergy": "Average energy", "trends.outOfFive": "/ 5", "trends.dueReviews": "Due reviews", "trends.upcomingReviews": "Next 7 days", "trends.studyChartTitle": "Study rhythm", "trends.studyChartDescription": "Completed study minutes by day.", "trends.srsTitle": "Review queue", "trends.srsDescription": "Mistakes enrolled in text flashcard review.", "trends.enrolled": "enrolled", "trends.due": "due now", "trends.nextSeven": "next 7 days", "trends.flashcardHint": "Open Flashcards to review the due queue.", "trends.subjectTitle": "Subject performance", "trends.subjectDescription": "Recent grades, mistakes and direction by subject.", "trends.grades": "grades", "trends.mistakes": "mistakes", "trends.latest": "latest", "trends.average": "average", "trends.dueMistakes": "due mistakes", "trends.latestRanking": "latest rank", "trends.averageRanking": "average rank", "trends.needsAttention": "Needs attention", "trends.noSubjects": "No subject trends yet", "trends.noSubjectsCopy": "Add grades or mistakes to see subject direction.", "trends.rising": "Rising", "trends.falling": "Falling", "trends.steady": "Steady",
  "flashcards.title": "Flashcards", "flashcards.description": "Turn enrolled mistakes into a focused text-only SRS session.", "flashcards.enrolled": "enrolled", "flashcards.summaryTitle": "Session complete", "flashcards.summaryCopy": "A small review session is still a useful return to the material.", "flashcards.reviewAgain": "Review again", "flashcards.progress": "{current} of {total}", "flashcards.question": "Question", "flashcards.answer": "Answer", "flashcards.reason": "Why it went wrong", "flashcards.wrongSolution": "Wrong solution", "flashcards.correctSolution": "Correct solution", "flashcards.clickQuestion": "Click to reveal the answer", "flashcards.clickAnswer": "Click to return to the question", "flashcards.again": "Again", "flashcards.againHint": "Requeue soon", "flashcards.hard": "Hard", "flashcards.hardHint": "Short interval", "flashcards.good": "Good", "flashcards.goodHint": "Normal interval", "flashcards.easy": "Easy", "flashcards.easyHint": "Long interval", "flashcards.empty": "Your review queue is clear", "flashcards.emptyDue": "There are no due cards right now.", "flashcards.emptyEnroll": "Enroll mistakes from the Mistakes page to build the queue.",
  "mistakes.enroll": "Add to review queue", "mistakes.easy": "Easy",
};

const p1ZhCN: Record<string, string> = {
  "nav.diary": "学习日记", "nav.trends": "趋势", "nav.flashcards": "闪卡",
  "diary.title": "学习日记", "diary.description": "记录心情、精力和今天学到的东西。", "diary.new": "新建记录", "diary.edit": "编辑记录", "diary.entryTitle": "今日状态", "diary.entryDescription": "同一天可以添加多条记录。", "diary.date": "日期", "diary.mood": "心情", "diary.energy": "精力", "diary.tag": "精力标签", "diary.tagPlaceholder": "例如：专注、疲惫", "diary.content": "Markdown 笔记", "diary.contentPlaceholder": "今天发生了什么？", "diary.update": "更新记录", "diary.save": "保存记录", "diary.cancel": "取消", "diary.trendTitle": "近期节奏", "diary.trendDescription": "最近 30 天的每日心情和精力。", "diary.activeDays": "活跃天数", "diary.studyMinutes": "学习分钟", "diary.energyShort": "精力", "diary.history": "日记历史", "diary.historyDescription": "记录保存在本地，随时可以回看。", "diary.delete": "删除", "diary.noContent": "没有笔记内容。", "diary.empty": "还没有日记记录", "diary.emptyCopy": "从一个心情和一句今日记录开始。", "diary.validationDate": "请选择日期。", "diary.confirmDelete": "删除这条日记记录吗？",
  "trends.title": "趋势", "trends.description": "查看学习时长、成绩、状态和复习之间的联系。", "trends.score": "分数", "trends.ranking": "排名", "trends.heatmapTitle": "90 天活动", "trends.heatmapDescription": "学习分钟 + 复习次数 + 成绩次数 × 5。", "trends.activeDays": "活跃天数", "trends.points": "活动点", "trends.streak": "连续天数", "trends.studyTime": "学习时长", "trends.range": "{start} – {end}", "trends.averageMood": "平均心情", "trends.averageEnergy": "平均精力", "trends.outOfFive": "/ 5", "trends.dueReviews": "到期复习", "trends.upcomingReviews": "未来 7 天", "trends.studyChartTitle": "学习节奏", "trends.studyChartDescription": "按天统计已完成的学习分钟。", "trends.srsTitle": "复习队列", "trends.srsDescription": "已加入文字闪卡复习的错题。", "trends.enrolled": "已入队", "trends.due": "当前到期", "trends.nextSeven": "未来 7 天", "trends.flashcardHint": "打开闪卡开始复习到期队列。", "trends.subjectTitle": "科目表现", "trends.subjectDescription": "按科目查看近期成绩、错题和方向。", "trends.grades": "成绩", "trends.mistakes": "错题", "trends.latest": "最近", "trends.average": "平均", "trends.dueMistakes": "到期错题", "trends.latestRanking": "最近排名", "trends.averageRanking": "平均排名", "trends.needsAttention": "需要关注", "trends.noSubjects": "还没有科目趋势", "trends.noSubjectsCopy": "添加成绩或错题后，这里会显示科目方向。", "trends.rising": "上升", "trends.falling": "下降", "trends.steady": "稳定",
  "flashcards.title": "闪卡", "flashcards.description": "把已入队错题变成专注的文字 SRS 复习。", "flashcards.enrolled": "已入队", "flashcards.summaryTitle": "本次复习完成", "flashcards.summaryCopy": "短暂复习也是一次回到材料的有效练习。", "flashcards.reviewAgain": "再次复习", "flashcards.progress": "{current} / {total}", "flashcards.question": "问题", "flashcards.answer": "答案", "flashcards.reason": "出错原因", "flashcards.wrongSolution": "错误解法", "flashcards.correctSolution": "正确解法", "flashcards.clickQuestion": "点击查看答案", "flashcards.clickAnswer": "点击返回问题", "flashcards.again": "再来一次", "flashcards.againHint": "很快重新出现", "flashcards.hard": "困难", "flashcards.hardHint": "较短间隔", "flashcards.good": "良好", "flashcards.goodHint": "正常间隔", "flashcards.easy": "简单", "flashcards.easyHint": "较长间隔", "flashcards.empty": "复习队列已清空", "flashcards.emptyDue": "现在没有到期闪卡。", "flashcards.emptyEnroll": "在错题页面将错题加入队列。",
  "mistakes.enroll": "加入复习队列", "mistakes.easy": "简单",
};

const p1ZhTW: Record<string, string> = {
  "nav.diary": "學習日記", "nav.trends": "趨勢", "nav.flashcards": "閃卡",
  "diary.title": "學習日記", "diary.description": "記錄心情、精力與今天學到的事。", "diary.new": "新增記錄", "diary.edit": "編輯記錄", "diary.entryTitle": "今日狀態", "diary.entryDescription": "同一天可以新增多筆記錄。", "diary.date": "日期", "diary.mood": "心情", "diary.energy": "精力", "diary.tag": "精力標籤", "diary.tagPlaceholder": "例如：專注、疲憊", "diary.content": "Markdown 筆記", "diary.contentPlaceholder": "今天發生了什麼？", "diary.update": "更新記錄", "diary.save": "儲存記錄", "diary.cancel": "取消", "diary.trendTitle": "近期節奏", "diary.trendDescription": "最近 30 天的每日心情與精力。", "diary.activeDays": "活躍天數", "diary.studyMinutes": "學習分鐘", "diary.energyShort": "精力", "diary.history": "日記歷史", "diary.historyDescription": "記錄保存在本機，隨時可以回看。", "diary.delete": "刪除", "diary.noContent": "沒有筆記內容。", "diary.empty": "還沒有日記記錄", "diary.emptyCopy": "從一個心情和一句今日記錄開始。", "diary.validationDate": "請選擇日期。", "diary.confirmDelete": "要刪除這筆日記記錄嗎？",
  "trends.title": "趨勢", "trends.description": "查看學習時長、成績、狀態與複習之間的關聯。", "trends.score": "分數", "trends.ranking": "排名", "trends.heatmapTitle": "90 天活動", "trends.heatmapDescription": "學習分鐘 + 複習次數 + 成績次數 × 5。", "trends.activeDays": "活躍天數", "trends.points": "活動點", "trends.streak": "連續天數", "trends.studyTime": "學習時長", "trends.range": "最近 90 天", "trends.averageMood": "平均心情", "trends.averageEnergy": "平均精力", "trends.outOfFive": "/ 5", "trends.dueReviews": "到期複習", "trends.upcomingReviews": "未來 7 天", "trends.studyChartTitle": "學習節奏", "trends.studyChartDescription": "按天統計已完成的學習分鐘。", "trends.srsTitle": "複習佇列", "trends.srsDescription": "已加入文字閃卡複習的錯題。", "trends.enrolled": "已入隊", "trends.due": "目前到期", "trends.nextSeven": "未來 7 天", "trends.flashcardHint": "開啟閃卡開始複習到期佇列。", "trends.subjectTitle": "科目表現", "trends.subjectDescription": "按科目查看近期成績、錯題與方向。", "trends.grades": "成績", "trends.mistakes": "錯題", "trends.latest": "最近", "trends.average": "平均", "trends.dueMistakes": "到期錯題", "trends.latestRanking": "最近排名", "trends.averageRanking": "平均排名", "trends.needsAttention": "需要關注", "trends.noSubjects": "還沒有科目趨勢", "trends.noSubjectsCopy": "新增成績或錯題後，這裡會顯示科目方向。", "trends.rising": "上升", "trends.falling": "下降", "trends.steady": "穩定",
  "flashcards.title": "閃卡", "flashcards.description": "把已入隊錯題變成專注的文字 SRS 複習。", "flashcards.enrolled": "已入隊", "flashcards.summaryTitle": "本次複習完成", "flashcards.summaryCopy": "短暫複習也是一次回到材料的有效練習。", "flashcards.reviewAgain": "再次複習", "flashcards.progress": "{current} / {total}", "flashcards.question": "問題", "flashcards.answer": "答案", "flashcards.reason": "出錯原因", "flashcards.wrongSolution": "錯誤解法", "flashcards.correctSolution": "正確解法", "flashcards.clickQuestion": "點擊查看答案", "flashcards.clickAnswer": "點擊返回問題", "flashcards.again": "再來一次", "flashcards.againHint": "很快重新出現", "flashcards.hard": "困難", "flashcards.hardHint": "較短間隔", "flashcards.good": "良好", "flashcards.goodHint": "正常間隔", "flashcards.easy": "簡單", "flashcards.easyHint": "較長間隔", "flashcards.empty": "複習佇列已清空", "flashcards.emptyDue": "現在沒有到期閃卡。", "flashcards.emptyEnroll": "在錯題頁面將錯題加入佇列。",
  "mistakes.enroll": "加入複習佇列", "mistakes.easy": "簡單",
};

const p1Ja: Record<string, string> = {
  "nav.diary": "学習日記", "nav.trends": "トレンド", "nav.flashcards": "フラッシュカード",
  "diary.title": "学習日記", "diary.description": "気分、エネルギー、今日学んだことを小さく記録します。", "diary.new": "新しい記録", "diary.edit": "記録を編集", "diary.entryTitle": "今日のチェックイン", "diary.entryDescription": "同じ日に複数の記録を追加できます。", "diary.date": "日付", "diary.mood": "気分", "diary.energy": "エネルギー", "diary.tag": "エネルギータグ", "diary.tagPlaceholder": "例：集中、疲れ", "diary.content": "Markdown メモ", "diary.contentPlaceholder": "今日はどうでしたか？", "diary.update": "記録を更新", "diary.save": "記録を保存", "diary.cancel": "キャンセル", "diary.trendTitle": "最近のリズム", "diary.trendDescription": "過去 30 日間の気分とエネルギー。", "diary.activeDays": "活動日", "diary.studyMinutes": "学習分", "diary.energyShort": "エネルギー", "diary.history": "日記の履歴", "diary.historyDescription": "記録はローカルに保存され、いつでも振り返れます。", "diary.delete": "削除", "diary.noContent": "メモはありません。", "diary.empty": "日記はまだありません", "diary.emptyCopy": "気分と今日の一文から始めましょう。", "diary.validationDate": "日付を選択してください。", "diary.confirmDelete": "この日記を削除しますか？",
  "trends.title": "トレンド", "trends.description": "学習時間、結果、状態、復習のつながりを確認します。", "trends.score": "得点", "trends.ranking": "順位", "trends.heatmapTitle": "90 日間の活動", "trends.heatmapDescription": "学習分 + 復習回数 + 成績回数 × 5。", "trends.activeDays": "活動日", "trends.points": "活動ポイント", "trends.streak": "日連続", "trends.studyTime": "学習時間", "trends.range": "過去 90 日", "trends.averageMood": "平均気分", "trends.averageEnergy": "平均エネルギー", "trends.outOfFive": "/ 5", "trends.dueReviews": "期限の復習", "trends.upcomingReviews": "次の 7 日間", "trends.studyChartTitle": "学習リズム", "trends.studyChartDescription": "完了した学習分を日ごとに表示します。", "trends.srsTitle": "復習キュー", "trends.srsDescription": "テキストフラッシュカードに登録した間違い。", "trends.enrolled": "登録済み", "trends.due": "今日期限", "trends.nextSeven": "次の 7 日", "trends.flashcardHint": "フラッシュカードを開いて期限のカードを復習しましょう。", "trends.subjectTitle": "科目の成績", "trends.subjectDescription": "科目ごとの最近の成績、間違い、方向性。", "trends.grades": "成績", "trends.mistakes": "間違い", "trends.latest": "最新", "trends.average": "平均", "trends.dueMistakes": "期限の間違い", "trends.latestRanking": "最新順位", "trends.averageRanking": "平均順位", "trends.needsAttention": "要確認", "trends.noSubjects": "科目トレンドはまだありません", "trends.noSubjectsCopy": "成績や間違いを追加すると科目の方向性が表示されます。", "trends.rising": "上昇", "trends.falling": "下降", "trends.steady": "安定",
  "flashcards.title": "フラッシュカード", "flashcards.description": "登録した間違いを集中したテキスト SRS セッションにします。", "flashcards.enrolled": "登録済み", "flashcards.summaryTitle": "セッション完了", "flashcards.summaryCopy": "短い復習でも、教材に戻る大切な一歩です。", "flashcards.reviewAgain": "もう一度復習", "flashcards.progress": "{current} / {total}", "flashcards.question": "問題", "flashcards.answer": "答え", "flashcards.reason": "間違えた理由", "flashcards.wrongSolution": "誤った解法", "flashcards.correctSolution": "正しい解法", "flashcards.clickQuestion": "クリックして問題に戻る", "flashcards.clickAnswer": "クリックして答えを見る", "flashcards.again": "もう一度", "flashcards.againHint": "すぐに再出題", "flashcards.hard": "難しい", "flashcards.hardHint": "短い間隔", "flashcards.good": "良い", "flashcards.goodHint": "通常の間隔", "flashcards.easy": "簡単", "flashcards.easyHint": "長い間隔", "flashcards.empty": "復習キューは空です", "flashcards.emptyDue": "今日期限のカードはありません。", "flashcards.emptyEnroll": "間違いページからカードをキューに登録してください。",
  "mistakes.enroll": "復習キューに追加", "mistakes.easy": "簡単",
};

const p1Ko: Record<string, string> = {
  "nav.diary": "학습 일기", "nav.trends": "추세", "nav.flashcards": "플래시카드",
  "diary.title": "학습 일기", "diary.description": "기분, 에너지와 오늘 배운 내용을 작게 기록하세요.", "diary.new": "새 기록", "diary.edit": "기록 편집", "diary.entryTitle": "오늘의 체크인", "diary.entryDescription": "같은 날에도 여러 기록을 추가할 수 있습니다.", "diary.date": "날짜", "diary.mood": "기분", "diary.energy": "에너지", "diary.tag": "에너지 태그", "diary.tagPlaceholder": "예: 집중, 피곤함", "diary.content": "Markdown 메모", "diary.contentPlaceholder": "오늘은 어땠나요?", "diary.update": "기록 업데이트", "diary.save": "기록 저장", "diary.cancel": "취소", "diary.trendTitle": "최근 리듬", "diary.trendDescription": "최근 30일의 기분과 에너지입니다.", "diary.activeDays": "활동 일수", "diary.studyMinutes": "학습 분", "diary.energyShort": "에너지", "diary.history": "일기 기록", "diary.historyDescription": "기록은 로컬에 저장되어 언제든 돌아볼 수 있습니다.", "diary.delete": "삭제", "diary.noContent": "메모 내용이 없습니다.", "diary.empty": "아직 일기가 없습니다", "diary.emptyCopy": "기분과 오늘의 한 문장으로 시작해 보세요.", "diary.validationDate": "날짜를 선택하세요.", "diary.confirmDelete": "이 일기 기록을 삭제할까요?",
  "trends.title": "추세", "trends.description": "학습 시간, 결과, 상태와 복습의 연결을 확인하세요.", "trends.score": "점수", "trends.ranking": "순위", "trends.heatmapTitle": "90일 활동", "trends.heatmapDescription": "학습 분 + 복습 횟수 + 성적 횟수 × 5.", "trends.activeDays": "활동 일수", "trends.points": "활동 포인트", "trends.streak": "일 연속", "trends.studyTime": "학습 시간", "trends.range": "최근 90일", "trends.averageMood": "평균 기분", "trends.averageEnergy": "평균 에너지", "trends.outOfFive": "/ 5", "trends.dueReviews": "복습 예정", "trends.upcomingReviews": "다음 7일", "trends.studyChartTitle": "학습 리듬", "trends.studyChartDescription": "완료한 학습 분을 날짜별로 보여 줍니다.", "trends.srsTitle": "복습 대기열", "trends.srsDescription": "텍스트 플래시카드 복습에 등록된 오답입니다.", "trends.enrolled": "등록됨", "trends.due": "현재 예정", "trends.nextSeven": "다음 7일", "trends.flashcardHint": "플래시카드를 열어 예정된 대기열을 복습하세요.", "trends.subjectTitle": "과목 성과", "trends.subjectDescription": "과목별 최근 성적, 오답과 방향입니다.", "trends.grades": "성적", "trends.mistakes": "오답", "trends.latest": "최근", "trends.average": "평균", "trends.dueMistakes": "복습할 오답", "trends.latestRanking": "최근 순위", "trends.averageRanking": "평균 순위", "trends.needsAttention": "관심 필요", "trends.noSubjects": "아직 과목 추세가 없습니다", "trends.noSubjectsCopy": "성적이나 오답을 추가하면 과목 방향이 표시됩니다.", "trends.rising": "상승", "trends.falling": "하락", "trends.steady": "안정",
  "flashcards.title": "플래시카드", "flashcards.description": "등록한 오답을 집중적인 텍스트 SRS 세션으로 바꿉니다.", "flashcards.enrolled": "등록됨", "flashcards.summaryTitle": "세션 완료", "flashcards.summaryCopy": "짧은 복습도 학습 내용으로 돌아가는 유용한 시간입니다.", "flashcards.reviewAgain": "다시 복습", "flashcards.progress": "{current} / {total}", "flashcards.question": "문제", "flashcards.answer": "답", "flashcards.reason": "틀린 이유", "flashcards.wrongSolution": "잘못된 풀이", "flashcards.correctSolution": "올바른 풀이", "flashcards.clickQuestion": "클릭해 문제로 돌아가기", "flashcards.clickAnswer": "클릭해 답 보기", "flashcards.again": "다시", "flashcards.againHint": "곧 다시 출제", "flashcards.hard": "어려움", "flashcards.hardHint": "짧은 간격", "flashcards.good": "좋음", "flashcards.goodHint": "일반 간격", "flashcards.easy": "쉬움", "flashcards.easyHint": "긴 간격", "flashcards.empty": "복습 대기열이 비었습니다", "flashcards.emptyDue": "지금 복습할 카드가 없습니다.", "flashcards.emptyEnroll": "오답 페이지에서 오답을 대기열에 등록하세요.",
  "mistakes.enroll": "복습 대기열에 추가", "mistakes.easy": "쉬움",
};

// P2 keys cover Coach, Exam Simulation, Reverse Planner, and Reports. The
// current dictionary map below intentionally exposes only the existing keys.
const p2En: Record<string, string> = {
  "exams.comprehensive": "Comprehensive exams", "exams.comprehensiveDescription": "Plan a combined exam across multiple subjects.", "exams.subjectsComma": "Subjects, comma separated", "exams.comprehensiveEmpty": "No comprehensive exams yet.",
  "nav.coach": "AI Coach", "nav.simulation": "Exam Simulator", "nav.planner": "Reverse Planner", "nav.reports": "Reports",
  "feature.providerRequired": "Connect Cloud AI or BYOK in Settings before generating or changing AI feature data.", "feature.saved": "Saved", "feature.draft": "Draft", "feature.working": "Working…", "common.send": "Send",
  "coach.title": "AI Coach", "coach.description": "Turn a score goal into evidence, risks and reviewable task proposals.", "coach.goalTitle": "Goal title", "coach.subject": "Subject", "coach.baseline": "Baseline score", "coach.target": "Target score", "coach.fullScore": "Full score", "coach.weight": "Subject weight", "coach.minutes": "Daily minutes", "coach.purpose": "Purpose", "coach.constraints": "Constraints", "coach.saveGoal": "Save goal", "coach.generate": "Analyze & propose", "coach.prediction": "Predicted score", "coach.probability": "Success probability", "coach.risks": "Risks", "coach.reject": "Reject", "coach.approve": "Approve tasks", "coach.chat": "Coach conversation", "coach.chatDescription": "Conversation is kept with the Coach goal.", "coach.chatPlaceholder": "Ask your coach…",
  "simulation.title": "Exam Simulator", "simulation.description": "A ten-question, twenty-minute session with autosave and behavior analysis.", "simulation.generate": "Generate 10 questions", "simulation.questions": "questions", "simulation.empty": "Generate a simulation to begin.", "simulation.start": "Start exam", "simulation.resume": "Resume exam", "simulation.previous": "Previous", "simulation.next": "Next", "simulation.submit": "Submit", "simulation.score": "Score", "simulation.answerPlaceholder": "Write your answer…",
  "planner.title": "Reverse Planner", "planner.description": "Start with the target score and work backward through weak points and daily routes.", "planner.examName": "Exam name", "planner.currentScore": "Current score", "planner.targetScore": "Target score", "planner.saveGoal": "Save exam goal", "planner.generate": "Generate route", "planner.savePlan": "Save plan", "planner.delete": "Delete", "planner.confirmDelete": "Delete this exam goal and its plan?", "planner.weakPoints": "Weak points", "planner.dailyTasks": "Daily route", "planner.empty": "Generate a plan to see weak points and daily tasks.", "planner.noGoal": "No exam goal yet", "planner.noGoalCopy": "Add an exam target above to build a route.",
  "reports.title": "Learning Reports", "reports.export": "Export StudyPulse report", "reports.studyTime": "Study time", "reports.sessions": "Sessions", "reports.score": "Score rate", "reports.mood": "Mood", "reports.share": "Share / open file",
  "mode.coach": "AI Coach", "mode.examSimulation": "Exam simulation", "mode.reversePlanner": "Reverse planner",
};

const p2ZhCN: Record<string, string> = {
  "exams.comprehensive": "综合考试", "exams.comprehensiveDescription": "为多个科目组合的综合考试建立计划。", "exams.subjectsComma": "科目，用逗号分隔", "exams.comprehensiveEmpty": "还没有综合考试。",
  "nav.coach": "AI 教练", "nav.simulation": "考试模拟", "nav.planner": "Reverse Planner", "nav.reports": "报告",
  "feature.providerRequired": "请先在设置中连接 Cloud AI 或 BYOK，才能生成或修改 AI 功能数据。", "feature.saved": "已保存", "feature.draft": "草稿", "feature.working": "处理中…", "common.send": "发送",
  "coach.title": "AI 教练", "coach.description": "把分数目标转成证据、风险和待审核任务建议。", "coach.goalTitle": "目标名称", "coach.subject": "科目", "coach.baseline": "基线分数", "coach.target": "目标分数", "coach.fullScore": "满分", "coach.weight": "科目权重", "coach.minutes": "每日分钟", "coach.purpose": "目的", "coach.constraints": "约束", "coach.saveGoal": "保存目标", "coach.generate": "分析并生成建议", "coach.prediction": "预测分数", "coach.probability": "达成概率", "coach.risks": "风险", "coach.reject": "拒绝", "coach.approve": "批准任务", "coach.chat": "教练对话", "coach.chatDescription": "对话会随 Coach 目标保存在本地。", "coach.chatPlaceholder": "问问你的教练…",
  "simulation.title": "考试模拟器", "simulation.description": "10 道题、20 分钟，自动保存并分析考试行为。", "simulation.generate": "生成 10 道题", "simulation.questions": "道题", "simulation.empty": "生成一次模拟考试开始。", "simulation.start": "开始考试", "simulation.resume": "恢复考试", "simulation.previous": "上一题", "simulation.next": "下一题", "simulation.submit": "交卷", "simulation.score": "得分", "simulation.answerPlaceholder": "写下你的答案…",
  "planner.title": "Reverse Planner", "planner.description": "从目标分数倒推薄弱点、阶段路线和每日任务。", "planner.examName": "考试名称", "planner.currentScore": "当前分数", "planner.targetScore": "目标分数", "planner.saveGoal": "保存考试目标", "planner.generate": "生成路线", "planner.savePlan": "保存计划", "planner.delete": "删除", "planner.confirmDelete": "删除这个考试目标和计划吗？", "planner.weakPoints": "薄弱点", "planner.dailyTasks": "每日路线", "planner.empty": "生成计划后会显示薄弱点和每日任务。", "planner.noGoal": "还没有考试目标", "planner.noGoalCopy": "先在上方添加考试目标。",
  "reports.title": "学习报告", "reports.export": "导出 StudyPulse 报告", "reports.studyTime": "学习时长", "reports.sessions": "学习 session", "reports.score": "成绩率", "reports.mood": "心情", "reports.share": "分享 / 打开文件",
  "mode.coach": "AI 教练", "mode.examSimulation": "考试模拟", "mode.reversePlanner": "Reverse Planner",
};

// Interface style labels are kept in a small complete five-language map so the
// independent Apple/Anthropic selector does not depend on P1/P2 dictionaries.
const interfaceStyleTranslations: Record<Language, Record<string, string>> = {
  en: {
    "settings.interfaceStyle": "Interface style", "settings.interfaceStyleDescription": "Choose the visual language for your workspace.", "style.anthropic": "Anthropic", "style.anthropicDescription": "Warm, editorial, reflective", "style.apple": "Apple", "style.appleDescription": "Clear, native, focused",
  },
  "zh-CN": {
    "settings.interfaceStyle": "界面风格", "settings.interfaceStyleDescription": "选择工作区使用的视觉语言。", "style.anthropic": "Anthropic", "style.anthropicDescription": "温暖、编辑感、沉静", "style.apple": "Apple", "style.appleDescription": "清晰、原生、专注",
  },
  "zh-TW": {
    "settings.interfaceStyle": "介面風格", "settings.interfaceStyleDescription": "選擇工作區使用的視覺語言。", "style.anthropic": "Anthropic", "style.anthropicDescription": "溫暖、編輯感、沉靜", "style.apple": "Apple", "style.appleDescription": "清晰、原生、專注",
  },
  ja: {
    "settings.interfaceStyle": "インターフェーススタイル", "settings.interfaceStyleDescription": "ワークスペースの視覚的な雰囲気を選択します。", "style.anthropic": "Anthropic", "style.anthropicDescription": "温かく、編集的で、落ち着いた", "style.apple": "Apple", "style.appleDescription": "明快で、ネイティブで、集中しやすい",
  },
  ko: {
    "settings.interfaceStyle": "인터페이스 스타일", "settings.interfaceStyleDescription": "워크스페이스의 시각 언어를 선택하세요.", "style.anthropic": "Anthropic", "style.anthropicDescription": "따뜻하고 편집적이며 차분함", "style.apple": "Apple", "style.appleDescription": "명확하고 네이티브하며 집중적",
  },
};

const agentSecurityTranslations: Record<Language, Record<string, string>> = {
  en: {
    "agent.localPythonWarning": "Local Python is not a security sandbox. If Docker Runner is not configured, this code runs with your account's host permissions.",
  },
  "zh-CN": {
    "agent.localPythonWarning": "本机 Python 不是安全沙箱。如果没有配置 Docker Runner，这段代码会以当前用户的主机权限运行。",
  },
  "zh-TW": {
    "agent.localPythonWarning": "本機 Python 不是安全沙箱。如果沒有設定 Docker Runner，這段程式碼會以目前使用者的主機權限執行。",
  },
  ja: {
    "agent.localPythonWarning": "ローカル Python は安全なサンドボックスではありません。Docker Runner を設定していない場合、このコードは現在のユーザー権限で実行されます。",
  },
  ko: {
    "agent.localPythonWarning": "로컬 Python은 보안 샌드박스가 아닙니다. Docker Runner를 구성하지 않으면 이 코드는 현재 계정의 호스트 권한으로 실행됩니다.",
  },
};

// Merge order matters: base language, style labels, then feature group. The
// zh-TW/ja/ko maps currently omit P2 bundles, so `t` falls back to English for
// those missing feature keys rather than pretending the bundles are complete.
const dictionaries: Record<Language, Record<string, string>> = {
  en: { ...en, ...interfaceStyleTranslations.en, ...agentSecurityTranslations.en, ...p1En, ...p2En },
  "zh-CN": { ...zhCN, ...interfaceStyleTranslations["zh-CN"], ...agentSecurityTranslations["zh-CN"], ...p1ZhCN, ...p2ZhCN },
  "zh-TW": { ...zhTW, ...interfaceStyleTranslations["zh-TW"], ...agentSecurityTranslations["zh-TW"], ...p1ZhTW, "planner.savePlan": "儲存計畫" },
  ja: { ...ja, ...interfaceStyleTranslations.ja, ...agentSecurityTranslations.ja, ...p1Ja, "planner.savePlan": "計画を保存" },
  ko: { ...ko, ...interfaceStyleTranslations.ko, ...agentSecurityTranslations.ko, ...p1Ko, "planner.savePlan": "계획 저장" },
};

function interpolate(template: string, variables?: Record<string, string | number>): string {
  // Only simple word placeholders are supported. A missing variable remains
  // visible as `{name}`, which makes incomplete call sites diagnosable.
  if (!variables) return template;
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(variables[key] ?? `{${key}}`));
}

export function languageLocale(language: Language): string {
  // Date/report APIs expect the conventional en-US locale while other app
  // languages already use the locale identifier accepted by Intl.
  return language === "en" ? "en-US" : language;
}

export function localizeEnum(t: Translate, prefix: string, value: string): string {
  // Enum labels are optional translations. Returning the original value keeps
  // new Core enum variants readable until a dictionary key is added.
  return t(`${prefix}.${value}`) === `${prefix}.${value}` ? value : t(`${prefix}.${value}`);
}

interface I18nValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: Translate;
}

const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  // The provider owns language state and persistence; consumers only receive a
  // stable translator that resolves the active dictionary on each language.
  const [language, setLanguageState] = useState<Language>(detectLanguage);
  const setLanguage = (next: Language) => {
    setLanguageState(next);
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, next);
  };
  const value = useMemo<I18nValue>(() => ({
    language,
    setLanguage,
    t: (key, variables) => interpolate(dictionaries[language][key] ?? en[key] ?? key, variables),
  }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nValue {
  // Failing at the hook boundary catches incorrectly mounted pages early,
  // rather than producing untranslated keys deep inside a component tree.
  const value = useContext(I18nContext);
  if (!value) throw new Error("useI18n must be used inside I18nProvider");
  return value;
}
